In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
from pathlib import Path

MOUTH_ROOT = Path(
    "/content/drive/MyDrive/AISC Çalışmalar/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output"
)

print("Klasör var mı?:", MOUTH_ROOT.exists())

if MOUTH_ROOT.exists():
    print("\nKlasör içeriği:")
    for item in sorted(MOUTH_ROOT.iterdir()):
        simge = "📁" if item.is_dir() else "📄"
        print(simge, item.name)
else:
    print("\nKlasör yolu bulunamadı. Drive'daki klasör yolunu yeniden kontrol et.")

Klasör var mı?: False

Klasör yolu bulunamadı. Drive'daki klasör yolunu yeniden kontrol et.

In [ ]:
from pathlib import Path

DRIVE_ROOT = Path("/content/drive/MyDrive")

bulunanlar = list(DRIVE_ROOT.rglob("mouth_roi_output"))

print("Bulunan klasör sayısı:", len(bulunanlar))

for yol in bulunanlar:
    print(yol)

Bulunan klasör sayısı: 0

In [ ]:
from pathlib import Path

DRIVE_ROOT = Path("/content/drive/MyDrive")

deney_klasorleri = [
    yol for yol in DRIVE_ROOT.rglob("Deney 1")
    if "Dilara" in str(yol)
]

print("Bulunan Deney 1 klasörü sayısı:", len(deney_klasorleri))

for deney_yolu in deney_klasorleri:
    print("\nDENey klasörü:", deney_yolu)
    print("İçeriği:")

    for item in sorted(deney_yolu.iterdir()):
        simge = "KLASÖR" if item.is_dir() else "DOSYA"
        print(f"  [{simge}] {item.name}")

Bulunan Deney 1 klasörü sayısı: 0

In [ ]:
from pathlib import Path
import pandas as pd

MOUTH_ROOT = Path(
    "/content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/"
    "Dilara/Deney 1/Ağız/mouth_roi_output"
)

MOUTH_METADATA = MOUTH_ROOT / "metadata.csv"

print("Ağız klasörü bulundu mu?:", MOUTH_ROOT.exists())
print("Metadata bulundu mu?:", MOUTH_METADATA.exists())

if MOUTH_ROOT.exists() and MOUTH_METADATA.exists():
    metadata = pd.read_csv(MOUTH_METADATA)

    image_extensions = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}

    real_count = sum(
        p.suffix.lower() in image_extensions
        for p in (MOUTH_ROOT / "real").rglob("*")
    )

    fake_count = sum(
        p.suffix.lower() in image_extensions
        for p in (MOUTH_ROOT / "fake").rglob("*")
    )

    print("\nMetadata satır sayısı:", len(metadata))
    print("Real görüntü sayısı:", real_count)
    print("Fake görüntü sayısı:", fake_count)
    print("Toplam görüntü sayısı:", real_count + fake_count)

    print("\nMetadata sütunları:")
    print(metadata.columns.tolist())

    print("\nİlk 5 satır:")
    display(metadata.head())

Ağız klasörü bulundu mu?: True
Metadata bulundu mu?: True

Metadata satır sayısı: 3098
Real görüntü sayısı: 2996
Fake görüntü sayısı: 2978
Toplam görüntü sayısı: 5974

Metadata sütunları:
['sample_id', 'source_frame', 'relative_frame_path', 'label', 'split', 'video_id', 'frame_stem', 'face_id', 'face_id_scope', 'faces_in_frame', 'mouth_detected', 'mouth_path', 'debug_path', 'landmarks_path', 'mouth_bbox_x1', 'mouth_bbox_y1', 'mouth_bbox_x2', 'mouth_bbox_y2', 'mouth_width_px', 'mouth_height_px', 'landmark_count', 'status', 'error', 'processing_ms']

İlk 5 satır:

,sample_id,source_frame,relative_frame_path,label,split,video_id,frame_stem,face_id,face_id_scope,faces_in_frame,...,mouth_bbox_x1,mouth_bbox_y1,mouth_bbox_x2,mouth_bbox_y2,mouth_width_px,mouth_height_px,landmark_count,status,error,processing_ms
0,fake_train_01130_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,fake_train_01130,0.0,frame,1,...,1275.0,370.0,1409.0,461.0,134.0,91.0,40,SUCCESS,NaN,395.327
1,fake_train_fake_train_01130_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,fake_train_01130,0.0,frame,1,...,1275.0,370.0,1409.0,461.0,134.0,91.0,40,SUCCESS,NaN,70.473
2,fake_train_fake_train_00000_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_00000.jpg,fake,train,fake_train_00000,fake_train_00000,0.0,frame,1,...,485.0,452.0,653.0,514.0,168.0,62.0,40,SUCCESS,NaN,56.912
3,fake_train_fake_train_00001_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_00001.jpg,fake,train,fake_train_00001,fake_train_00001,0.0,frame,1,...,317.0,152.0,371.0,181.0,54.0,29.0,40,SUCCESS,NaN,43.924
4,fake_train_fake_train_00002_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_00002.jpg,fake,train,fake_train_00002,fake_train_00002,0.0,frame,1,...,381.0,217.0,463.0,255.0,82.0,38.0,40,SUCCESS,NaN,53.329

In [ ]:
import pandas as pd
from pathlib import Path

metadata = pd.read_csv(MOUTH_METADATA)

print("TÜM METADATA SÜTUNLARI:")
for i, column in enumerate(metadata.columns, start=1):
    print(f"{i:02d}. {column}")

print("\nTOPLAM METADATA SATIRI:", len(metadata))
print("BENZERSİZ SAMPLE_ID:", metadata["sample_id"].nunique())
print("MÜKERRER SAMPLE_ID:", metadata["sample_id"].duplicated().sum())

for column in ["label", "split", "status", "skip_reason"]:
    if column in metadata.columns:
        print(f"\n{column.upper()} DAĞILIMI:")
        print(metadata[column].fillna("EMPTY").value_counts(dropna=False))

print("\nLABEL × SPLIT TABLOSU:")
print(pd.crosstab(metadata["split"], metadata["label"], margins=True))

print("\nDOSYA YOLU İÇEREBİLECEK SÜTUNLAR:")
path_columns = [
    column for column in metadata.columns
    if "path" in column.lower() or "output" in column.lower()
]
print(path_columns)

display(metadata.head(3))

TÜM METADATA SÜTUNLARI:
01. sample_id
02. source_frame
03. relative_frame_path
04. label
05. split
06. video_id
07. frame_stem
08. face_id
09. face_id_scope
10. faces_in_frame
11. mouth_detected
12. mouth_path
13. debug_path
14. landmarks_path
15. mouth_bbox_x1
16. mouth_bbox_y1
17. mouth_bbox_x2
18. mouth_bbox_y2
19. mouth_width_px
20. mouth_height_px
21. landmark_count
22. status
23. error
24. processing_ms

TOPLAM METADATA SATIRI: 3098
BENZERSİZ SAMPLE_ID: 3098
MÜKERRER SAMPLE_ID: 0

LABEL DAĞILIMI:
label
fake    1567
real    1531
Name: count, dtype: int64

SPLIT DAĞILIMI:
split
train    2479
test      310
val       309
Name: count, dtype: int64

STATUS DAĞILIMI:
status
SUCCESS    2987
SKIPPED     111
Name: count, dtype: int64

LABEL × SPLIT TABLOSU:
label  fake  real   All
split
test    159   151   310
train  1254  1225  2479
val     154   155   309
All    1567  1531  3098

DOSYA YOLU İÇEREBİLECEK SÜTUNLAR:
['relative_frame_path', 'mouth_path', 'debug_path', 'landmarks_path']

,sample_id,source_frame,relative_frame_path,label,split,video_id,frame_stem,face_id,face_id_scope,faces_in_frame,...,mouth_bbox_x1,mouth_bbox_y1,mouth_bbox_x2,mouth_bbox_y2,mouth_width_px,mouth_height_px,landmark_count,status,error,processing_ms
0,fake_train_01130_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,fake_train_01130,0.0,frame,1,...,1275.0,370.0,1409.0,461.0,134.0,91.0,40,SUCCESS,NaN,395.327
1,fake_train_fake_train_01130_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,fake_train_01130,0.0,frame,1,...,1275.0,370.0,1409.0,461.0,134.0,91.0,40,SUCCESS,NaN,70.473
2,fake_train_fake_train_00000_face00,/content/drive/MyDrive/AISC Çalışmalar/Deney...,Fake/train/fake_train_00000.jpg,fake,train,fake_train_00000,fake_train_00000,0.0,frame,1,...,485.0,452.0,653.0,514.0,168.0,62.0,40,SUCCESS,NaN,56.912

In [ ]:
metadata = pd.read_csv(MOUTH_METADATA)

# Aynı kaynak frame'in kaç kez metadata'ya yazıldığını kontrol et
duplicate_mask = metadata.duplicated(
    subset=["relative_frame_path", "face_id"],
    keep=False
)

duplicates = metadata.loc[
    duplicate_mask,
    [
        "sample_id",
        "relative_frame_path",
        "label",
        "split",
        "video_id",
        "face_id",
        "status",
        "mouth_path",
        "debug_path"
    ]
].sort_values(["relative_frame_path", "face_id"])

print("Toplam metadata satırı:", len(metadata))
print(
    "Benzersiz frame + face kaydı:",
    metadata[["relative_frame_path", "face_id"]]
    .drop_duplicates()
    .shape[0]
)
print("Tekrarlı gruplardaki toplam satır:", len(duplicates))
print(
    "Tekrarlanan fazladan kayıt sayısı:",
    metadata.duplicated(
        subset=["relative_frame_path", "face_id"],
        keep="first"
    ).sum()
)

print("\nTekrarlı kayıt örnekleri:")
display(duplicates.head(20))

Toplam metadata satırı: 3098
Benzersiz frame + face kaydı: 3097
Tekrarlı gruplardaki toplam satır: 2
Tekrarlanan fazladan kayıt sayısı: 1

Tekrarlı kayıt örnekleri:

,sample_id,relative_frame_path,label,split,video_id,face_id,status,mouth_path,debug_path
0,fake_train_01130_face00,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,0.0,SUCCESS,/content/drive/MyDrive/AISC Çalışmalar/Deney...,/content/drive/MyDrive/AISC Çalışmalar/Deney...
1,fake_train_fake_train_01130_face00,Fake/train/fake_train_01130.jpg,fake,train,fake_train_01130,0.0,SUCCESS,/content/drive/MyDrive/AISC Çalışmalar/Deney...,/content/drive/MyDrive/AISC Çalışmalar/Deney...

In [ ]:
metadata = pd.read_csv(MOUTH_METADATA)

print("Toplam metadata satırı:", len(metadata))
print(
    "Benzersiz kaynak frame:",
    metadata["relative_frame_path"].nunique()
)

print("\nFACE_ID DAĞILIMI:")
print(metadata["face_id"].fillna(-1).value_counts().sort_index())

frame_counts = (
    metadata.groupby("relative_frame_path")
    .size()
    .sort_values(ascending=False)
)

print("\nBir metadata satırı bulunan frame sayısı:")
print((frame_counts == 1).sum())

print("\nBirden fazla metadata satırı bulunan frame sayısı:")
print((frame_counts > 1).sum())

print("\nFrame başına en yüksek kayıt sayısı:")
print(frame_counts.max())

print("\nBirden fazla yüz/kayıt bulunan örnek frameler:")
display(frame_counts[frame_counts > 1].head(20))

Toplam metadata satırı: 3098
Benzersiz kaynak frame: 3000

FACE_ID DAĞILIMI:
face_id
-1.0     111
 0.0    2890
 1.0      93
 2.0       3
 3.0       1
Name: count, dtype: int64

Bir metadata satırı bulunan frame sayısı:
2906

Birden fazla metadata satırı bulunan frame sayısı:
94

Frame başına en yüksek kayıt sayısı:
4

Birden fazla yüz/kayıt bulunan örnek frameler:

relative_frame_path
Real/train/real_train_00138.jpg    4
Real/val/real_val_00108.jpg        3
Real/train/real_train_00487.jpg    3
Fake/train/fake_train_01059.jpg    2
Fake/train/fake_train_00028.jpg    2
Fake/train/fake_train_00933.jpg    2
Fake/test/fake_test_00088.jpg      2
Fake/train/fake_train_00033.jpg    2
Fake/train/fake_train_00936.jpg    2
Fake/train/fake_train_00707.jpg    2
Fake/train/fake_train_00202.jpg    2
Fake/train/fake_train_00705.jpg    2
Real/train/real_train_01010.jpg    2
Fake/train/fake_train_00703.jpg    2
Real/train/real_train_00130.jpg    2
Fake/train/fake_train_00476.jpg    2
Fake/train/fake_train_00208.jpg    2
Fake/test/fake_test_00075.jpg      2
Fake/test/fake_test_00074.jpg      2
Fake/val/fake_val_00048.jpg        2
dtype: int64

In [ ]:
# 1) Colab bağımlılıkları
# HOG ve LBP özellik çıkarımı, SVM eğitimi ve güvenli kayıt işlemleri için gereklidir.

!pip -q install scikit-image scikit-learn pyyaml joblib opencv-python-headless

In [ ]:
# 2) Merkezi YAML konfigürasyonunu oluştur ve yükle

from pathlib import Path
import yaml

CONFIG_PATH = Path("/content/hog_lbp_svm_mouth.yaml")

DEFAULT_CONFIG_YAML = """
seed: 42
region: mouth
model_name: hog_lbp_svm

image_width: 128
image_height: 64

hog:
  orientations: 9
  pixels_per_cell: [8, 8]
  cells_per_block: [2, 2]
  block_norm: L2-Hys

lbp:
  points: 8
  radius: 1
  method: uniform

svm:
  class_weight: balanced
  selection_metric: f1
  kernels: [linear, rbf]
  c_values: [0.1, 1.0, 10.0]
  gamma_values: [scale, 0.001, 0.0001]

positive_class: fake
figure_dpi: 150
minimum_figure_short_edge_px: 600
resume_run_id: null

data_root: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output
roi_metadata_path: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output/metadata.csv
selection_metadata_path: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Deney 1 Frame/secim_metadata.csv
results_root: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar
"""

# Bu notebook için ağız konfigürasyonunu güncel ve kesin biçimde oluştur.
CONFIG_PATH.write_text(DEFAULT_CONFIG_YAML.strip(), encoding="utf-8")

try:
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        CONFIG = yaml.safe_load(file)

except yaml.YAMLError as error:
    backup_path = CONFIG_PATH.with_suffix(".yaml.broken")

    if CONFIG_PATH.exists():
        CONFIG_PATH.replace(backup_path)

    CONFIG_PATH.write_text(
        DEFAULT_CONFIG_YAML.strip(),
        encoding="utf-8"
    )

    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        CONFIG = yaml.safe_load(file)

    print("Bozuk YAML yenilendi:", backup_path)
    print("Önceki YAML hatası:", error)

print(yaml.safe_dump(
    CONFIG,
    sort_keys=False,
    allow_unicode=True
))

seed: 42
region: mouth
model_name: hog_lbp_svm
image_width: 128
image_height: 64
hog:
  orientations: 9
  pixels_per_cell:
  - 8
  - 8
  cells_per_block:
  - 2
  - 2
  block_norm: L2-Hys
lbp:
  points: 8
  radius: 1
  method: uniform
svm:
  class_weight: balanced
  selection_metric: f1
  kernels:
  - linear
  - rbf
  c_values:
  - 0.1
  - 1.0
  - 10.0
  gamma_values:
  - scale
  - 0.001
  - 0.0001
positive_class: fake
figure_dpi: 150
minimum_figure_short_edge_px: 600
resume_run_id: null
data_root: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney
  1/Ağız/mouth_roi_output
roi_metadata_path: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney
  1/Ağız/mouth_roi_output/metadata.csv
selection_metadata_path: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Deney
  1 Frame/secim_metadata.csv
results_root: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney
  1/Sonuçlar

In [ ]:
# 3) Imports, reproducibility, run klasörleri ve yardımcı fonksiyonlar

import os
import sys
import json
import time
import random
import hashlib
import logging
import platform
import subprocess

from datetime import datetime
from pathlib import Path

import cv2
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image
from skimage.feature import hog, local_binary_pattern

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    roc_curve,
    precision_recall_curve,
    ConfusionMatrixDisplay,
)


# ---------------------------------------------------------
# Tekrar üretilebilirlik
# ---------------------------------------------------------

SEED = int(CONFIG["seed"])

random.seed(SEED)
np.random.seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)


# ---------------------------------------------------------
# Drive yolları
# ---------------------------------------------------------

DATA_ROOT = Path(CONFIG["data_root"])
ROI_METADATA_PATH = Path(CONFIG["roi_metadata_path"])
SELECTION_METADATA_PATH = Path(CONFIG["selection_metadata_path"])
RESULTS_ROOT = Path(CONFIG["results_root"])


# Girdi yolları doğrulanmadan sonuç klasörü oluşturulmaz.
assert DATA_ROOT.exists(), f"Ağız ROI klasörü bulunamadı: {DATA_ROOT}"
assert ROI_METADATA_PATH.exists(), (
    f"Ağız metadata dosyası bulunamadı: {ROI_METADATA_PATH}"
)
assert SELECTION_METADATA_PATH.exists(), (
    f"Seçim metadata dosyası bulunamadı: {SELECTION_METADATA_PATH}"
)


# ---------------------------------------------------------
# Deney kimliği ve sonuç klasörleri
# ---------------------------------------------------------

resume_run_id = CONFIG.get("resume_run_id")

if resume_run_id:
    RUN_ID = str(resume_run_id)
else:
    RUN_ID = (
        datetime.now().strftime("%Y%m%d_%H%M")
        + f"_mouth_hog_lbp_svm_seed{SEED}"
    )

RUN_DIR = RESULTS_ROOT / RUN_ID

if RUN_DIR.exists() and not resume_run_id:
    raise FileExistsError(
        f"Bu run_id zaten mevcut: {RUN_DIR}. "
        "Aynı dizine iki farklı deney yazılmaz. "
        "Yeni bir dakika bekleyin veya resume_run_id kullanın."
    )

DIRS = {
    "checkpoints": RUN_DIR / "checkpoints",
    "logs": RUN_DIR / "logs",
    "metrics": RUN_DIR / "metrics",
    "predictions": RUN_DIR / "predictions",
    "figures": RUN_DIR / "figures",
    "artifacts": RUN_DIR / "artifacts",
}

for path in [RUN_DIR, *DIRS.values()]:
    path.mkdir(parents=True, exist_ok=True)


# Kaynak ağız ROI klasörüne sonuç yazılmasını engelle.
assert RUN_DIR.resolve() != DATA_ROOT.resolve()
assert DATA_ROOT.resolve() not in RUN_DIR.resolve().parents


# ---------------------------------------------------------
# Logger
# ---------------------------------------------------------

LOG_PATH = DIRS["logs"] / "run.log"

logger = logging.getLogger("mouth_hog_lbp_svm")
logger.setLevel(logging.INFO)
logger.handlers.clear()

formatter = logging.Formatter(
    "%(asctime)s | %(levelname)s | %(message)s"
)

file_handler = logging.FileHandler(
    LOG_PATH,
    encoding="utf-8"
)
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setFormatter(formatter)
logger.addHandler(stream_handler)


# ---------------------------------------------------------
# Güvenli JSON dönüşümü
# ---------------------------------------------------------

def json_safe(value):
    if isinstance(value, dict):
        return {
            str(key): json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, np.integer):
        return int(value)

    if isinstance(value, np.floating):
        return float(value)

    if isinstance(value, Path):
        return str(value)

    return value


# ---------------------------------------------------------
# Atomik dosya kayıt fonksiyonları
# ---------------------------------------------------------

def write_json_atomic(data, target: Path):
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")

    with temporary.open("w", encoding="utf-8") as file:
        json.dump(
            json_safe(data),
            file,
            ensure_ascii=False,
            indent=2
        )
        file.flush()
        os.fsync(file.fileno())

    with temporary.open("r", encoding="utf-8") as file:
        json.load(file)

    os.replace(temporary, target)


def write_csv_atomic(dataframe: pd.DataFrame, target: Path):
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")

    dataframe.to_csv(temporary, index=False)
    pd.read_csv(temporary)

    os.replace(temporary, target)


def save_npz_atomic(target: Path, **arrays):
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")

    with temporary.open("wb") as file:
        np.savez_compressed(file, **arrays)
        file.flush()
        os.fsync(file.fileno())

    with np.load(temporary, allow_pickle=False) as loaded:
        if not loaded.files:
            raise RuntimeError(
                f"NPZ doğrulaması başarısız: {temporary}"
            )

    os.replace(temporary, target)


def atomic_joblib_dump(obj, target: Path, required_keys=None):
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")

    joblib.dump(obj, temporary)
    loaded = joblib.load(temporary)

    if required_keys:
        valid = (
            isinstance(loaded, dict)
            and set(required_keys).issubset(loaded.keys())
        )

        if not valid:
            raise RuntimeError(
                f"Checkpoint doğrulaması başarısız: {temporary}"
            )

    os.replace(temporary, target)


def sha256_file(path: Path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()

    with path.open("rb") as file:
        for chunk in iter(
            lambda: file.read(chunk_size),
            b""
        ):
            digest.update(chunk)

    return digest.hexdigest()


def save_figure(fig, target: Path):
    fig.tight_layout()

    fig.savefig(
        target,
        dpi=int(CONFIG["figure_dpi"]),
        bbox_inches="tight"
    )

    plt.close(fig)

    with Image.open(target) as image:
        width, height = image.size

    minimum_edge = int(
        CONFIG["minimum_figure_short_edge_px"]
    )

    assert min(width, height) >= minimum_edge, (
        f"Grafik çözünürlüğü yetersiz: {(width, height)}"
    )

    return width, height


# ---------------------------------------------------------
# Çözümlenmiş konfigürasyonu kaydet
# ---------------------------------------------------------

resolved_config = dict(CONFIG)

resolved_config.update({
    "run_id": RUN_ID,
    "run_dir": str(RUN_DIR),
    "created_at": datetime.now().isoformat(),
})

with (RUN_DIR / "config_resolved.yaml").open(
    "w",
    encoding="utf-8"
) as file:
    yaml.safe_dump(
        resolved_config,
        file,
        sort_keys=False,
        allow_unicode=True
    )


logger.info("RUN_ID=%s", RUN_ID)
logger.info("Ağız ROI girdisi=%s", DATA_ROOT)
logger.info("Deney çıktısı=%s", RUN_DIR)

print("\nBaşlangıç kontrolleri: PASS")
print("Run ID:", RUN_ID)
print("Sonuç klasörü:", RUN_DIR)

2026-08-07 20:34:43,517 | INFO | RUN_ID=20260807_2034_mouth_hog_lbp_svm_seed42

INFO:mouth_hog_lbp_svm:RUN_ID=20260807_2034_mouth_hog_lbp_svm_seed42

2026-08-07 20:34:43,520 | INFO | Ağız ROI girdisi=/content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output

INFO:mouth_hog_lbp_svm:Ağız ROI girdisi=/content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output

2026-08-07 20:34:43,522 | INFO | Deney çıktısı=/content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar/20260807_2034_mouth_hog_lbp_svm_seed42

INFO:mouth_hog_lbp_svm:Deney çıktısı=/content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar/20260807_2034_mouth_hog_lbp_svm_seed42

Başlangıç kontrolleri: PASS
Run ID: 20260807_2034_mouth_hog_lbp_svm_seed42
Sonuç klasörü: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar/20260807_2034_mouth_hog_lbp_svm_seed42

In [ ]:
# Metadata içindeki ağız ROI yollarının geçerliliğini kontrol et

raw_metadata = pd.read_csv(ROI_METADATA_PATH)

success_rows = raw_metadata[
    raw_metadata["status"].astype(str).str.upper() == "SUCCESS"
].copy()

success_rows["mouth_path_exists"] = success_rows["mouth_path"].apply(
    lambda path: Path(str(path)).exists()
)

print("SUCCESS kayıt sayısı:", len(success_rows))
print(
    "Mevcut mouth_path sayısı:",
    int(success_rows["mouth_path_exists"].sum())
)
print(
    "Bulunamayan mouth_path sayısı:",
    int((~success_rows["mouth_path_exists"]).sum())
)

print("\nİlk mouth_path:")
print(success_rows["mouth_path"].iloc[0])

print("\nİlk yol diskte var mı?:")
print(Path(str(success_rows["mouth_path"].iloc[0])).exists())

SUCCESS kayıt sayısı: 2987
Mevcut mouth_path sayısı: 0
Bulunamayan mouth_path sayısı: 2987

İlk mouth_path:
/content/drive/MyDrive/AISC Çalışmalar/Deneyler/Dilara/Deney 1/Ağız/mouth_roi_output/fake/train/mouth/fake_train_01130_face00.png

İlk yol diskte var mı?:
False

In [14]:
# 4) Ağız metadata hazırlama, eski yolları düzeltme,
# veri muhasebesi ve kaynak-video sızıntısı kontrolleri

import re


# =========================================================
# 1. Metadata dosyalarını oku
# =========================================================

roi = pd.read_csv(ROI_METADATA_PATH)

selection = pd.read_csv(
    SELECTION_METADATA_PATH,
    encoding="utf-8-sig"
)


# =========================================================
# 2. Zorunlu sütunları doğrula
# =========================================================

required_roi_columns = {
    "sample_id",
    "source_frame",
    "relative_frame_path",
    "label",
    "split",
    "video_id",
    "frame_stem",
    "face_id",
    "faces_in_frame",
    "mouth_detected",
    "mouth_path",
    "debug_path",
    "landmarks_path",
    "mouth_bbox_x1",
    "mouth_bbox_y1",
    "mouth_bbox_x2",
    "mouth_bbox_y2",
    "mouth_width_px",
    "mouth_height_px",
    "landmark_count",
    "status",
    "error",
    "processing_ms",
}

required_selection_columns = {
    "sinif",
    "split",
    "orijinal_yol",
    "yeni_yol",
    "dosya_adi",
}

missing_roi_columns = (
    required_roi_columns - set(roi.columns)
)

missing_selection_columns = (
    required_selection_columns - set(selection.columns)
)

assert not missing_roi_columns, (
    "Ağız metadata dosyasında eksik sütunlar var: "
    f"{sorted(missing_roi_columns)}"
)

assert not missing_selection_columns, (
    "Seçim metadata dosyasında eksik sütunlar var: "
    f"{sorted(missing_selection_columns)}"
)


# =========================================================
# 3. Metadata içindeki eski mouth_path yollarını düzelt
# =========================================================
#
# Metadata yollarında eski üst klasör:
# /content/drive/MyDrive/AISC Çalışmaları/...
#
# Güncel üst klasör:
# /content/drive/MyDrive/AISC DeepFake Çalışmaları/...
#
# Drive'daki metadata.csv değiştirilmez.
# Yol yalnızca bu Colab oturumunda düzeltilir.

def resolve_mouth_path(raw_path):
    if pd.isna(raw_path):
        return ""

    raw_path = str(raw_path).strip()

    if raw_path == "":
        return ""

    path = Path(raw_path)
    path_parts = path.parts

    if "mouth_roi_output" in path_parts:
        root_index = path_parts.index(
            "mouth_roi_output"
        )

        relative_parts = path_parts[
            root_index + 1:
        ]

        resolved_path = DATA_ROOT.joinpath(
            *relative_parts
        )

        return str(resolved_path)

    return str(path)


roi = roi.copy()

roi["resolved_mouth_path"] = (
    roi["mouth_path"].apply(resolve_mouth_path)
)


# =========================================================
# 4. Kaynak frame ile seçim metadata'sını eşleştir
# =========================================================

selection = selection.copy()

selection["dosya_adi"] = (
    selection["dosya_adi"].astype(str)
)

assert selection["dosya_adi"].is_unique, (
    "secim_metadata.csv içinde dosya_adi "
    "değerleri benzersiz değil."
)


# Orijinal video adı gerçek kaynak yoldan alınır.
selection["source_video_resolved"] = (
    selection["orijinal_yol"].map(
        lambda path: Path(str(path)).parent.name
    )
)


def extract_original_frame_index(path):
    frame_stem = Path(str(path)).stem
    match = re.search(r"(\d+)$", frame_stem)

    if match is None:
        raise ValueError(
            "Frame numarası orijinal yoldan "
            f"çıkarılamadı: {path}"
        )

    return int(match.group(1))


selection["original_frame_index"] = (
    selection["orijinal_yol"].map(
        extract_original_frame_index
    )
)


# Ağız metadata'sındaki göreli frame yolundan
# yalnızca dosya adını al.
roi["selected_frame_name"] = (
    roi["relative_frame_path"].map(
        lambda path: Path(str(path)).name
    )
)


# Bir kaynak frame'den birden fazla yüz çıkabildiği için
# many_to_one eşleştirme kullanılır.
merged = roi.merge(
    selection[
        [
            "dosya_adi",
            "source_video_resolved",
            "original_frame_index",
            "orijinal_yol",
        ]
    ],
    left_on="selected_frame_name",
    right_on="dosya_adi",
    how="left",
    validate="many_to_one",
)


assert merged["source_video_resolved"].notna().all(), (
    "Bazı ağız ROI kayıtları "
    "secim_metadata.csv ile eşleşmedi."
)


# =========================================================
# 5. Ekip standardına uygun metadata oluştur
# =========================================================

status_values = (
    merged["status"]
    .fillna("ERROR")
    .astype(str)
    .str.upper()
)


metadata = pd.DataFrame({
    "sample_id": (
        merged["sample_id"].astype(str)
    ),

    "source_video": (
        merged["source_video_resolved"]
        .astype(str)
    ),

    "frame_index": (
        merged["original_frame_index"]
        .astype(int)
    ),

    "face_index": (
        merged["face_id"]
        .fillna(0)
        .astype(int)
    ),

    "roi_state": np.where(
        status_values == "SUCCESS",
        "mouth_detected",
        "mouth_not_detected",
    ),

    "label": (
        merged["label"]
        .astype(str)
        .str.lower()
    ),

    "split": (
        merged["split"]
        .astype(str)
        .str.lower()
    ),

    "status": status_values,

    "skip_reason": np.where(
        status_values == "SKIPPED",
        merged["error"]
        .fillna("MOUTH_NOT_DETECTED")
        .astype(str),
        "",
    ),

    # Başarılı ağız ROI dosyaları için aşağıda doldurulur.
    "sha256": "",

    "output_path": (
        merged["resolved_mouth_path"]
        .astype(str)
    ),

    # Model eğitim run kimliği
    "run_id": RUN_ID,

    "original_path": (
        merged["orijinal_yol"]
        .astype(str)
    ),

    "selected_frame_name": (
        merged["selected_frame_name"]
        .astype(str)
    ),

    "faces_in_frame": (
        merged["faces_in_frame"]
        .fillna(0)
        .astype(int)
    ),

    "mouth_width_px": (
        merged["mouth_width_px"]
    ),

    "mouth_height_px": (
        merged["mouth_height_px"]
    ),
})


# =========================================================
# 6. Metadata şemasını ve dağılımları doğrula
# =========================================================

assert len(metadata) == 3098, (
    "Beklenen metadata satır sayısı 3098, "
    f"bulunan: {len(metadata)}"
)

assert metadata["sample_id"].is_unique, (
    "Mükerrer sample_id tespit edildi."
)

assert set(metadata["label"].unique()) == {
    "real",
    "fake",
}, metadata["label"].value_counts().to_dict()

assert set(metadata["split"].unique()) == {
    "train",
    "val",
    "test",
}, metadata["split"].value_counts().to_dict()

assert set(
    metadata["status"].unique()
).issubset({
    "SUCCESS",
    "SKIPPED",
    "ERROR",
})


# =========================================================
# 7. Veri muhasebesi
# =========================================================

total_inputs = len(metadata)

success_count = int(
    (metadata["status"] == "SUCCESS").sum()
)

skipped_count = int(
    (metadata["status"] == "SKIPPED").sum()
)

error_count = int(
    (metadata["status"] == "ERROR").sum()
)


assert (
    total_inputs
    == success_count
    + skipped_count
    + error_count
), "Girdi-çıktı sayıları uyuşmuyor."


# Model yalnızca SUCCESS durumundaki ağız ROI'lerini kullanır.
eligible = metadata.loc[
    metadata["status"] == "SUCCESS"
].copy().reset_index(drop=True)


assert len(eligible) == 2987, (
    "Beklenen başarılı ağız ROI sayısı 2987, "
    f"bulunan: {len(eligible)}"
)


# =========================================================
# 8. Başarılı ağız ROI dosyalarının varlığını doğrula
# =========================================================

missing_success_files = [
    path
    for path in eligible["output_path"]
    if not Path(path).exists()
]


assert not missing_success_files, (
    "SUCCESS durumundaki "
    f"{len(missing_success_files)} ağız ROI "
    "dosyası diskte bulunamadı."
)


# =========================================================
# 9. Dosya bütünlük hash'lerini hesapla
# =========================================================
#
# DÜZELTME:
# sha256_file fonksiyonuna metin yerine Path nesnesi verilir.

eligible["sha256"] = (
    eligible["output_path"].map(
        lambda path: sha256_file(Path(path))
    )
)


# Hesaplanan hash değerlerini ana metadata tablosuna aktar.
success_mask = (
    metadata["status"] == "SUCCESS"
)

metadata.loc[
    success_mask,
    "sha256",
] = eligible["sha256"].to_numpy()


assert (
    eligible["sha256"].astype(str).str.len() == 64
).all(), "Geçersiz SHA-256 değeri tespit edildi."


# =========================================================
# 10. Kaynak-video düzeyinde veri sızıntısı kontrolü
# =================================================================

video_sets = {
    split_name: set(
        eligible.loc[
            eligible["split"] == split_name,
            "source_video",
        ].astype(str)
    )
    for split_name in [
        "train",
        "val",
        "test",
    ]
}


intersections = {
    "train_val": len(
        video_sets["train"]
        & video_sets["val"]
    ),

    "train_test": len(
        video_sets["train"]
        & video_sets["test"]
    ),

    "val_test": len(
        video_sets["val"]
        & video_sets["test"]
    ),
}


assert intersections["train_val"] == 0, (
    "Train ve validation arasında "
    "kaynak-video sızıntısı var."
)

assert intersections["train_test"] == 0, (
    "Train ve test arasında "
    "kaynak-video sızıntısı var."
)

assert intersections["val_test"] == 0, (
    "Validation ve test arasında "
    "kaynak-video sızıntısı var."
)


# Bir kaynak video yalnızca tek splitte bulunmalıdır.
assert (
    eligible.groupby("source_video")["split"]
    .nunique()
    .max()
    == 1
), "Aynı kaynak video birden fazla splitte bulunuyor."


# Bir kaynak video yalnızca tek gerçek sınıfa ait olmalıdır.
assert (
    eligible.groupby("source_video")["label"]
    .nunique()
    .max()
    == 1
), "Aynı kaynak video birden fazla label ile eşleşiyor."


# =========================================================
# 11. Split ve sınıf dağılımları
# =========================================================

split_class_counts = (
    eligible.groupby(["split", "label"])
    .size()
    .unstack(fill_value=0)
    .to_dict(orient="index")
)


split_source_video_counts = {
    split_name: int(
        eligible.loc[
            eligible["split"] == split_name,
            "source_video",
        ].nunique()
    )
    for split_name in [
        "train",
        "val",
        "test",
    ]
}


# =========================================================
# 12. Veri muhasebesi sonuçlarını kaydet
# =========================================================

accounting = {
    "run_id": RUN_ID,

    "total_metadata_rows": total_inputs,

    "unique_source_frames": int(
        metadata["selected_frame_name"].nunique()
    ),

    "success_count": success_count,

    "skipped_count": skipped_count,

    "error_count": error_count,

    "training_eligible_success_count": int(
        len(eligible)
    ),

    "unique_source_videos": int(
        eligible["source_video"].nunique()
    ),

    "split_class_counts": split_class_counts,

    "split_source_video_counts": (
        split_source_video_counts
    ),

    "source_video_intersections": (
        intersections
    ),
}


write_json_atomic(
    accounting,
    DIRS["metrics"] / "data_accounting.json"
)


write_csv_atomic(
    metadata,
    DIRS["artifacts"] / "metadata_used.csv"
)


# =========================================================
# 13. Sonuçları göster
# =========================================================

print(json.dumps(
    accounting,
    ensure_ascii=False,
    indent=2
))

print(
    "\nMetadata and leakage quality gates: PASS"
)

{
  "run_id": "20260807_2034_mouth_hog_lbp_svm_seed42",
  "total_metadata_rows": 3098,
  "unique_source_frames": 3000,
  "success_count": 2987,
  "skipped_count": 111,
  "error_count": 0,
  "training_eligible_success_count": 2987,
  "unique_source_videos": 1940,
  "split_class_counts": {
    "test": {
      "fake": 156,
      "real": 146
    },
    "train": {
      "fake": 1192,
      "real": 1197
    },
    "val": {
      "fake": 141,
      "real": 155
    }
  },
  "split_source_video_counts": {
    "train": 1557,
    "val": 187,
    "test": 196
  },
  "source_video_intersections": {
    "train_val": 0,
    "train_test": 0,
    "val_test": 0
  }
}

Metadata and leakage quality gates: PASS

In [15]:
# 5) HOG + LBP özellik çıkarımı ve klasik ML smoke testi

IMG_W = int(CONFIG["image_width"])
IMG_H = int(CONFIG["image_height"])

HOG_CFG = CONFIG["hog"]
LBP_CFG = CONFIG["lbp"]


# =========================================================
# 1. Ağız ROI görüntüsünü oku ve ön işle
# =========================================================

def load_preprocessed_grayscale(path: str) -> np.ndarray:
    image = cv2.imread(
        str(path),
        cv2.IMREAD_GRAYSCALE
    )

    if image is None:
        raise ValueError(
            f"Ağız ROI görüntüsü okunamadı: {path}"
        )

    image = cv2.resize(
        image,
        (IMG_W, IMG_H),
        interpolation=cv2.INTER_AREA
    )

    if image.dtype != np.uint8:
        image = np.clip(
            image,
            0,
            255
        ).astype(np.uint8)

    return image


# =========================================================
# 2. HOG özelliklerini çıkar
# =========================================================

def extract_hog(gray: np.ndarray) -> np.ndarray:
    features = hog(
        gray,
        orientations=int(
            HOG_CFG["orientations"]
        ),
        pixels_per_cell=tuple(
            HOG_CFG["pixels_per_cell"]
        ),
        cells_per_block=tuple(
            HOG_CFG["cells_per_block"]
        ),
        block_norm=str(
            HOG_CFG["block_norm"]
        ),
        feature_vector=True,
    )

    return np.asarray(
        features,
        dtype=np.float32
    )


# =========================================================
# 3. LBP özelliklerini çıkar
# =========================================================

def extract_lbp(gray: np.ndarray) -> np.ndarray:
    points = int(LBP_CFG["points"])
    radius = int(LBP_CFG["radius"])
    method = str(LBP_CFG["method"])

    lbp_image = local_binary_pattern(
        gray,
        P=points,
        R=radius,
        method=method
    )

    if method == "uniform":
        number_of_bins = points + 2
    else:
        number_of_bins = int(
            lbp_image.max() + 1
        )

    histogram, _ = np.histogram(
        lbp_image.ravel(),
        bins=np.arange(
            0,
            number_of_bins + 1
        ),
        range=(0, number_of_bins)
    )

    histogram = histogram.astype(
        np.float32
    )

    histogram /= (
        histogram.sum() + 1e-12
    )

    return histogram


# =========================================================
# 4. HOG ve LBP özelliklerini birleştir
# =========================================================

def extract_features(path: str):
    gray = load_preprocessed_grayscale(
        path
    )

    hog_features = extract_hog(gray)
    lbp_features = extract_lbp(gray)

    fused_features = np.concatenate(
        [
            hog_features,
            lbp_features,
        ]
    ).astype(np.float32)

    if not np.isfinite(
        fused_features
    ).all():
        raise FloatingPointError(
            "HOG/LBP özelliklerinde NaN veya Inf "
            f"tespit edildi: {path}"
        )

    return (
        hog_features,
        lbp_features,
        fused_features,
    )


# =========================================================
# 5. Smoke test için iki Real ve iki Fake train örneği
# =========================================================

smoke_rows = pd.concat(
    [
        eligible[
            (eligible["split"] == "train")
            & (eligible["label"] == "real")
        ].head(2),

        eligible[
            (eligible["split"] == "train")
            & (eligible["label"] == "fake")
        ].head(2),
    ],
    ignore_index=True
)


assert len(smoke_rows) == 4, (
    "Smoke test için dört örnek bulunamadı."
)

assert smoke_rows["label"].nunique() == 2, (
    "Smoke test iki sınıfı da içermiyor."
)


# =========================================================
# 6. Özellik çıkarımı + SVM fit/predict smoke testi
# =========================================================

smoke_X = []
smoke_y = []

for row in smoke_rows.itertuples(
    index=False
):
    _, _, fused = extract_features(
        row.output_path
    )

    smoke_X.append(fused)

    smoke_y.append(
        1
        if row.label
        == CONFIG["positive_class"]
        else 0
    )


smoke_X = np.vstack(smoke_X)

smoke_y = np.asarray(
    smoke_y,
    dtype=np.int64
)


assert np.isfinite(smoke_X).all(), (
    "Smoke test özelliklerinde NaN/Inf var."
)


smoke_scaler = StandardScaler()

smoke_X_scaled = smoke_scaler.fit_transform(
    smoke_X
)


smoke_model = SVC(
    kernel="linear",
    C=1.0,
    class_weight="balanced"
)

smoke_model.fit(
    smoke_X_scaled,
    smoke_y
)


smoke_predictions = smoke_model.predict(
    smoke_X_scaled
)


assert len(smoke_predictions) == len(
    smoke_y
)


print("Classical-ML smoke test: PASS")
print("Smoke sample count:", len(smoke_y))
print("HOG dimension:", len(extract_hog(
    load_preprocessed_grayscale(
        smoke_rows.iloc[0]["output_path"]
    )
)))
print("LBP dimension:", len(extract_lbp(
    load_preprocessed_grayscale(
        smoke_rows.iloc[0]["output_path"]
    )
)))
print("Fused feature dimension:", smoke_X.shape[1])

Classical-ML smoke test: PASS
Smoke sample count: 4
HOG dimension: 3780
LBP dimension: 10
Fused feature dimension: 3790

In [16]:
# 6) Train, validation ve test için HOG + LBP özellik çıkarımı
# Her split tamamlandığında atomik NPZ cache olarak Drive'a kaydedilir.

def build_split_features(split_name: str):
    cache_path = (
        DIRS["artifacts"]
        / f"features_{split_name}.npz"
    )

    # Split daha önce tamamlandıysa tekrar hesaplama.
    if cache_path.exists():
        logger.info(
            "Cached features loaded: %s",
            cache_path
        )

        with np.load(
            cache_path,
            allow_pickle=False
        ) as loaded:
            return {
                "X_hog": loaded["X_hog"],
                "X_lbp": loaded["X_lbp"],
                "X_fused": loaded["X_fused"],
                "y": loaded["y"],
                "sample_id": (
                    loaded["sample_id"].astype(str)
                ),
                "source_video": (
                    loaded["source_video"].astype(str)
                ),
                "frame_index": (
                    loaded["frame_index"]
                ),
                "output_path": (
                    loaded["output_path"].astype(str)
                ),
            }

    split_data = eligible.loc[
        eligible["split"] == split_name
    ].copy().reset_index(drop=True)

    assert len(split_data) > 0, (
        f"{split_name} splitinde örnek bulunamadı."
    )

    hog_rows = []
    lbp_rows = []
    fused_rows = []
    labels = []

    start_time = time.time()

    for index, row in enumerate(
        split_data.itertuples(index=False),
        start=1
    ):
        hog_features, lbp_features, fused_features = (
            extract_features(row.output_path)
        )

        hog_rows.append(hog_features)
        lbp_rows.append(lbp_features)
        fused_rows.append(fused_features)

        labels.append(
            1
            if row.label
            == CONFIG["positive_class"]
            else 0
        )

        if (
            index % 100 == 0
            or index == len(split_data)
        ):
            elapsed_minutes = (
                time.time() - start_time
            ) / 60

            logger.info(
                "Feature extraction %s: %d/%d | %.2f min",
                split_name,
                index,
                len(split_data),
                elapsed_minutes,
            )

    split_features = {
        "X_hog": np.vstack(
            hog_rows
        ).astype(np.float32),

        "X_lbp": np.vstack(
            lbp_rows
        ).astype(np.float32),

        "X_fused": np.vstack(
            fused_rows
        ).astype(np.float32),

        "y": np.asarray(
            labels,
            dtype=np.int64
        ),

        "sample_id": split_data[
            "sample_id"
        ].astype(str).to_numpy(),

        "source_video": split_data[
            "source_video"
        ].astype(str).to_numpy(),

        "frame_index": split_data[
            "frame_index"
        ].to_numpy(dtype=np.int64),

        "output_path": split_data[
            "output_path"
        ].astype(str).to_numpy(),
    }

    assert np.isfinite(
        split_features["X_fused"]
    ).all(), (
        f"{split_name} özelliklerinde NaN/Inf var."
    )

    assert (
        len(split_features["X_fused"])
        == len(split_data)
    )

    save_npz_atomic(
        cache_path,
        **split_features
    )

    logger.info(
        "Feature extraction %s completed in %.2f min",
        split_name,
        (time.time() - start_time) / 60,
    )

    return split_features


features = {}

for split_name in [
    "train",
    "val",
    "test",
]:
    features[split_name] = (
        build_split_features(split_name)
    )


# Temel boyut doğrulamaları
feature_dimensions = {
    "hog": int(
        features["train"]["X_hog"].shape[1]
    ),
    "lbp": int(
        features["train"]["X_lbp"].shape[1]
    ),
    "fused": int(
        features["train"]["X_fused"].shape[1]
    ),
}


assert feature_dimensions == {
    "hog": 3780,
    "lbp": 10,
    "fused": 3790,
}, feature_dimensions


for split_name in [
    "train",
    "val",
    "test",
]:
    print(
        split_name,
        features[split_name]["X_fused"].shape,
        "Real:",
        int(
            (
                features[split_name]["y"] == 0
            ).sum()
        ),
        "Fake:",
        int(
            (
                features[split_name]["y"] == 1
            ).sum()
        ),
    )

print("\nFeature extraction quality gate: PASS")
print("Feature dimensions:", feature_dimensions)

2026-08-07 22:25:02,968 | INFO | Feature extraction train: 100/2389 | 0.05 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 100/2389 | 0.05 min

2026-08-07 22:25:04,396 | INFO | Feature extraction train: 200/2389 | 0.07 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 200/2389 | 0.07 min

2026-08-07 22:25:05,536 | INFO | Feature extraction train: 300/2389 | 0.09 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 300/2389 | 0.09 min

2026-08-07 22:25:06,606 | INFO | Feature extraction train: 400/2389 | 0.11 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 400/2389 | 0.11 min

2026-08-07 22:25:07,699 | INFO | Feature extraction train: 500/2389 | 0.13 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 500/2389 | 0.13 min

2026-08-07 22:25:08,777 | INFO | Feature extraction train: 600/2389 | 0.15 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 600/2389 | 0.15 min

2026-08-07 22:25:09,856 | INFO | Feature extraction train: 700/2389 | 0.16 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 700/2389 | 0.16 min

2026-08-07 22:25:11,269 | INFO | Feature extraction train: 800/2389 | 0.19 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 800/2389 | 0.19 min

2026-08-07 22:25:12,340 | INFO | Feature extraction train: 900/2389 | 0.21 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 900/2389 | 0.21 min

2026-08-07 22:25:13,410 | INFO | Feature extraction train: 1000/2389 | 0.22 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1000/2389 | 0.22 min

2026-08-07 22:25:14,480 | INFO | Feature extraction train: 1100/2389 | 0.24 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1100/2389 | 0.24 min

2026-08-07 22:25:15,838 | INFO | Feature extraction train: 1200/2389 | 0.26 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1200/2389 | 0.26 min

2026-08-07 22:25:17,311 | INFO | Feature extraction train: 1300/2389 | 0.29 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1300/2389 | 0.29 min

2026-08-07 22:25:18,703 | INFO | Feature extraction train: 1400/2389 | 0.31 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1400/2389 | 0.31 min

2026-08-07 22:25:19,867 | INFO | Feature extraction train: 1500/2389 | 0.33 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1500/2389 | 0.33 min

2026-08-07 22:25:20,962 | INFO | Feature extraction train: 1600/2389 | 0.35 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1600/2389 | 0.35 min

2026-08-07 22:25:22,045 | INFO | Feature extraction train: 1700/2389 | 0.37 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1700/2389 | 0.37 min

2026-08-07 22:25:23,153 | INFO | Feature extraction train: 1800/2389 | 0.39 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1800/2389 | 0.39 min

2026-08-07 22:25:24,251 | INFO | Feature extraction train: 1900/2389 | 0.40 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 1900/2389 | 0.40 min

2026-08-07 22:25:25,351 | INFO | Feature extraction train: 2000/2389 | 0.42 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 2000/2389 | 0.42 min

2026-08-07 22:25:26,432 | INFO | Feature extraction train: 2100/2389 | 0.44 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 2100/2389 | 0.44 min

2026-08-07 22:25:27,581 | INFO | Feature extraction train: 2200/2389 | 0.46 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 2200/2389 | 0.46 min

2026-08-07 22:25:28,662 | INFO | Feature extraction train: 2300/2389 | 0.48 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 2300/2389 | 0.48 min

2026-08-07 22:25:29,861 | INFO | Feature extraction train: 2389/2389 | 0.50 min

INFO:mouth_hog_lbp_svm:Feature extraction train: 2389/2389 | 0.50 min

2026-08-07 22:25:33,906 | INFO | Feature extraction train completed in 0.57 min

INFO:mouth_hog_lbp_svm:Feature extraction train completed in 0.57 min

2026-08-07 22:25:35,034 | INFO | Feature extraction val: 100/296 | 0.02 min

INFO:mouth_hog_lbp_svm:Feature extraction val: 100/296 | 0.02 min

2026-08-07 22:25:36,141 | INFO | Feature extraction val: 200/296 | 0.04 min

INFO:mouth_hog_lbp_svm:Feature extraction val: 200/296 | 0.04 min

2026-08-07 22:25:37,208 | INFO | Feature extraction val: 296/296 | 0.05 min

INFO:mouth_hog_lbp_svm:Feature extraction val: 296/296 | 0.05 min

2026-08-07 22:25:37,635 | INFO | Feature extraction val completed in 0.06 min

INFO:mouth_hog_lbp_svm:Feature extraction val completed in 0.06 min

2026-08-07 22:25:38,729 | INFO | Feature extraction test: 100/302 | 0.02 min

INFO:mouth_hog_lbp_svm:Feature extraction test: 100/302 | 0.02 min

2026-08-07 22:25:39,835 | INFO | Feature extraction test: 200/302 | 0.04 min

INFO:mouth_hog_lbp_svm:Feature extraction test: 200/302 | 0.04 min

2026-08-07 22:25:41,106 | INFO | Feature extraction test: 300/302 | 0.06 min

INFO:mouth_hog_lbp_svm:Feature extraction test: 300/302 | 0.06 min

2026-08-07 22:25:41,133 | INFO | Feature extraction test: 302/302 | 0.06 min

INFO:mouth_hog_lbp_svm:Feature extraction test: 302/302 | 0.06 min

2026-08-07 22:25:41,566 | INFO | Feature extraction test completed in 0.07 min

INFO:mouth_hog_lbp_svm:Feature extraction test completed in 0.07 min

train (2389, 3790) Real: 1197 Fake: 1192
val (296, 3790) Real: 155 Fake: 141
test (302, 3790) Real: 146 Fake: 156

Feature extraction quality gate: PASS
Feature dimensions: {'hog': 3780, 'lbp': 10, 'fused': 3790}

In [17]:
# 7) Train-only StandardScaler +
# validation-only SVM ve threshold seçimi

# =========================================================
# 1. Train, validation ve test özelliklerini hazırla
# =========================================================

X_train = features["train"]["X_fused"]
y_train = features["train"]["y"]

X_val = features["val"]["X_fused"]
y_val = features["val"]["y"]

X_test = features["test"]["X_fused"]
y_test = features["test"]["y"]


assert X_train.shape[1] == 3790
assert X_val.shape[1] == 3790
assert X_test.shape[1] == 3790

assert set(np.unique(y_train)) == {0, 1}
assert set(np.unique(y_val)) == {0, 1}
assert set(np.unique(y_test)) == {0, 1}


# =========================================================
# 2. StandardScaler yalnızca train üzerinde öğrenilir
# =========================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_val_scaled = scaler.transform(
    X_val
)


# Test burada ölçeklenmez.
# Test setine yalnızca nihai değerlendirme hücresinde bakılacak.

assert np.isfinite(
    X_train_scaled
).all()

assert np.isfinite(
    X_val_scaled
).all()


feature_pipeline = {
    "input": "mouth ROI",
    "grayscale": True,
    "resize": [
        int(CONFIG["image_width"]),
        int(CONFIG["image_height"]),
    ],
    "hog": CONFIG["hog"],
    "lbp": CONFIG["lbp"],
    "fusion": "HOG + LBP concatenation",
    "scaler": "StandardScaler fitted on train only",
    "feature_dimensions": feature_dimensions,
}


# =========================================================
# 3. Değerlendirme metrikleri
# =========================================================

def metrics_from_scores(
    y_true,
    decision_scores,
    threshold
):
    y_true = np.asarray(y_true)
    decision_scores = np.asarray(
        decision_scores
    )

    y_prediction = (
        decision_scores >= threshold
    ).astype(np.int64)

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_prediction,
        labels=[0, 1]
    ).ravel()

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0.0
    )

    recall = recall_score(
        y_true,
        y_prediction,
        zero_division=0
    )

    balanced_accuracy = (
        recall + specificity
    ) / 2.0

    return {
        "accuracy": accuracy_score(
            y_true,
            y_prediction
        ),

        "precision": precision_score(
            y_true,
            y_prediction,
            zero_division=0
        ),

        "recall": recall,

        "specificity": specificity,

        "balanced_accuracy": (
            balanced_accuracy
        ),

        "f1": f1_score(
            y_true,
            y_prediction,
            zero_division=0
        ),

        "roc_auc": roc_auc_score(
            y_true,
            decision_scores
        ),

        "average_precision": (
            average_precision_score(
                y_true,
                decision_scores
            )
        ),

        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }


# =========================================================
# 4. Validation setinde en iyi F1 threshold'unu bul
# =========================================================

def find_best_f1_threshold(
    y_true,
    decision_scores
):
    precision_values, recall_values, thresholds = (
        precision_recall_curve(
            y_true,
            decision_scores
        )
    )

    if len(thresholds) == 0:
        return 0.0

    f1_values = (
        2
        * precision_values[:-1]
        * recall_values[:-1]
        / (
            precision_values[:-1]
            + recall_values[:-1]
            + 1e-12
        )
    )

    best_index = int(
        np.nanargmax(f1_values)
    )

    return float(
        thresholds[best_index]
    )


# =========================================================
# 5. SVM adaylarını oluştur
# =========================================================

svm_config = CONFIG["svm"]

candidates = []

for kernel in svm_config["kernels"]:
    for c_value in svm_config["c_values"]:

        if kernel == "linear":
            candidates.append({
                "kernel": "linear",
                "C": float(c_value),
                "gamma": None,
            })

        elif kernel == "rbf":
            for gamma_value in (
                svm_config["gamma_values"]
            ):
                candidates.append({
                    "kernel": "rbf",
                    "C": float(c_value),
                    "gamma": gamma_value,
                })

        else:
            raise ValueError(
                f"Desteklenmeyen kernel: {kernel}"
            )


assert len(candidates) == 12, (
    f"Beklenen SVM aday sayısı 12, "
    f"bulunan: {len(candidates)}"
)

print("SVM candidate count:", len(candidates))


# =========================================================
# 6. Bütün adayları yalnızca validation ile değerlendir
# =========================================================

search_rows = []
search_start_time = time.time()

for candidate_index, parameters in enumerate(
    candidates,
    start=1
):
    model_parameters = {
        "kernel": parameters["kernel"],
        "C": parameters["C"],
        "class_weight": (
            svm_config["class_weight"]
        ),
        "probability": False,
        "cache_size": 2048,
    }

    if parameters["kernel"] == "rbf":
        model_parameters["gamma"] = (
            parameters["gamma"]
        )

    candidate_model = SVC(
        **model_parameters
    )

    candidate_start_time = time.time()

    candidate_model.fit(
        X_train_scaled,
        y_train
    )

    validation_scores = (
        candidate_model.decision_function(
            X_val_scaled
        )
    )

    assert np.isfinite(
        validation_scores
    ).all(), (
        "Validation karar skorlarında "
        "NaN veya Inf tespit edildi."
    )

    candidate_threshold = (
        find_best_f1_threshold(
            y_val,
            validation_scores
        )
    )

    candidate_metrics = (
        metrics_from_scores(
            y_val,
            validation_scores,
            candidate_threshold
        )
    )

    search_row = {
        **parameters,
        "threshold": candidate_threshold,

        **{
            f"val_{metric_name}": float(
                metric_value
            )
            for metric_name, metric_value
            in candidate_metrics.items()
        },

        "fit_seconds": (
            time.time()
            - candidate_start_time
        ),
    }

    search_rows.append(search_row)

    # Her adaydan sonra sonuçları Drive'a kaydet.
    write_csv_atomic(
        pd.DataFrame(search_rows),
        DIRS["metrics"]
        / "svm_validation_search.csv"
    )

    logger.info(
        "SVM candidate %d/%d | %s | val_f1=%.4f",
        candidate_index,
        len(candidates),
        parameters,
        candidate_metrics["f1"],
    )


# =========================================================
# 7. En iyi SVM adayını validation sonucuna göre seç
# =========================================================

search_dataframe = pd.DataFrame(
    search_rows
)

search_dataframe = (
    search_dataframe.sort_values(
        [
            "val_f1",
            "val_roc_auc",
            "val_accuracy",
        ],
        ascending=[
            False,
            False,
            False,
        ],
    )
    .reset_index(drop=True)
)


best_row = (
    search_dataframe.iloc[0].to_dict()
)


best_model_parameters = {
    "kernel": best_row["kernel"],
    "C": float(best_row["C"]),
    "class_weight": (
        svm_config["class_weight"]
    ),
    "probability": False,
    "cache_size": 2048,
}


if best_row["kernel"] == "rbf":
    best_model_parameters["gamma"] = (
        best_row["gamma"]
    )


# En iyi parametrelerle model yalnızca train üzerinde eğitilir.
best_model = SVC(
    **best_model_parameters
)

best_model.fit(
    X_train_scaled,
    y_train
)


selected_threshold = float(
    best_row["threshold"]
)


# =========================================================
# 8. Model seçim özetini oluştur
# =========================================================

raw_gamma = best_row.get("gamma")

if pd.isna(raw_gamma):
    selected_gamma = None
else:
    selected_gamma = raw_gamma


selection_summary = {
    "selection_set": "validation",

    "selection_metric": (
        svm_config["selection_metric"]
    ),

    "kernel": best_row["kernel"],

    "C": float(best_row["C"]),

    "gamma": selected_gamma,

    "threshold": selected_threshold,

    "validation_metrics": {
        key.replace("val_", ""): float(value)
        for key, value in best_row.items()
        if str(key).startswith("val_")
    },

    "candidate_count": len(candidates),

    "search_seconds": (
        time.time() - search_start_time
    ),

    "test_set_used_for_selection": False,
}


write_json_atomic(
    selection_summary,
    DIRS["metrics"] / "svm_selection.json"
)


# =========================================================
# 9. Kullanılabilir model dosyasını atomik kaydet
# =========================================================

model_artifact = {
    "model": best_model,
    "scaler": scaler,
    "threshold": selected_threshold,
    "positive_class": (
        CONFIG["positive_class"]
    ),
    "feature_pipeline": feature_pipeline,
    "config": resolved_config,
}


atomic_joblib_dump(
    model_artifact,
    DIRS["artifacts"] / "svm_model.joblib",
    required_keys=[
        "model",
        "scaler",
        "threshold",
    ],
)


# =========================================================
# 10. Sonucu göster
# =========================================================

print("\nSelected SVM:")
print(json.dumps(
    json_safe(selection_summary),
    ensure_ascii=False,
    indent=2
))

print(
    "\nTrain-only scaling and "
    "validation-only model selection: PASS"
)

SVM candidate count: 12
2026-08-07 22:31:01,205 | INFO | SVM candidate 1/12 | {'kernel': 'linear', 'C': 0.1, 'gamma': None} | val_f1=0.6453

INFO:mouth_hog_lbp_svm:SVM candidate 1/12 | {'kernel': 'linear', 'C': 0.1, 'gamma': None} | val_f1=0.6453

2026-08-07 22:31:26,288 | INFO | SVM candidate 2/12 | {'kernel': 'linear', 'C': 1.0, 'gamma': None} | val_f1=0.6453

INFO:mouth_hog_lbp_svm:SVM candidate 2/12 | {'kernel': 'linear', 'C': 1.0, 'gamma': None} | val_f1=0.6453

2026-08-07 22:31:51,810 | INFO | SVM candidate 3/12 | {'kernel': 'linear', 'C': 10.0, 'gamma': None} | val_f1=0.6453

INFO:mouth_hog_lbp_svm:SVM candidate 3/12 | {'kernel': 'linear', 'C': 10.0, 'gamma': None} | val_f1=0.6453

2026-08-07 22:32:10,136 | INFO | SVM candidate 4/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 'scale'} | val_f1=0.6473

INFO:mouth_hog_lbp_svm:SVM candidate 4/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 'scale'} | val_f1=0.6473

2026-08-07 22:32:28,198 | INFO | SVM candidate 5/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 0.001} | val_f1=0.6498

INFO:mouth_hog_lbp_svm:SVM candidate 5/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 0.001} | val_f1=0.6498

2026-08-07 22:32:48,170 | INFO | SVM candidate 6/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 0.0001} | val_f1=0.6509

INFO:mouth_hog_lbp_svm:SVM candidate 6/12 | {'kernel': 'rbf', 'C': 0.1, 'gamma': 0.0001} | val_f1=0.6509

2026-08-07 22:33:05,346 | INFO | SVM candidate 7/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 'scale'} | val_f1=0.6944

INFO:mouth_hog_lbp_svm:SVM candidate 7/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 'scale'} | val_f1=0.6944

2026-08-07 22:33:22,936 | INFO | SVM candidate 8/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 0.001} | val_f1=0.6995

INFO:mouth_hog_lbp_svm:SVM candidate 8/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 0.001} | val_f1=0.6995

2026-08-07 22:33:40,358 | INFO | SVM candidate 9/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 0.0001} | val_f1=0.6834

INFO:mouth_hog_lbp_svm:SVM candidate 9/12 | {'kernel': 'rbf', 'C': 1.0, 'gamma': 0.0001} | val_f1=0.6834

2026-08-07 22:33:58,108 | INFO | SVM candidate 10/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 'scale'} | val_f1=0.6848

INFO:mouth_hog_lbp_svm:SVM candidate 10/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 'scale'} | val_f1=0.6848

2026-08-07 22:34:16,087 | INFO | SVM candidate 11/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 0.001} | val_f1=0.6957

INFO:mouth_hog_lbp_svm:SVM candidate 11/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 0.001} | val_f1=0.6957

2026-08-07 22:34:31,960 | INFO | SVM candidate 12/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 0.0001} | val_f1=0.6875

INFO:mouth_hog_lbp_svm:SVM candidate 12/12 | {'kernel': 'rbf', 'C': 10.0, 'gamma': 0.0001} | val_f1=0.6875

Selected SVM:
{
  "selection_set": "validation",
  "selection_metric": "f1",
  "kernel": "rbf",
  "C": 1.0,
  "gamma": 0.001,
  "threshold": -0.14414598526723613,
  "validation_metrics": {
    "accuracy": 0.6283783783783784,
    "precision": 0.5688888888888889,
    "recall": 0.9078014184397163,
    "specificity": 0.3741935483870968,
    "balanced_accuracy": 0.6409974834134066,
    "f1": 0.6994535519125683,
    "roc_auc": 0.7165179592770534,
    "average_precision": 0.6718237141597949,
    "tn": 58.0,
    "fp": 97.0,
    "fn": 13.0,
    "tp": 128.0
  },
  "candidate_count": 12,
  "search_seconds": 251.3162100315094,
  "test_set_used_for_selection": false
}

Train-only scaling and validation-only model selection: PASS

In [18]:
# 8) Atomik klasik ML checkpoint ve
# sıfırdan model yükleme kalite kontrolleri

# =========================================================
# 1. Klasik ML checkpoint içeriğini oluştur
# =========================================================

checkpoint_state = {
    "checkpoint_schema": "classical_ml_v1",

    "training_stage": "completed_svm_fit",

    # SVC epoch tabanlı çalışmadığı için uygulanamaz.
    "epoch": None,

    "model": best_model,

    "preprocessor": scaler,

    "threshold": selected_threshold,

    "positive_class": (
        CONFIG["positive_class"]
    ),

    "feature_pipeline": feature_pipeline,

    "config": resolved_config,

    "best_metric_score": float(
        best_row["val_f1"]
    ),

    "python_random_state": (
        random.getstate()
    ),

    "numpy_random_state": (
        np.random.get_state()
    ),

    "non_applicable_pytorch_fields": {
        "model_state_dict": (
            "N/A - sklearn SVC object is "
            "serialized as a complete object"
        ),

        "optimizer_state_dict": (
            "N/A - sklearn SVC has no "
            "PyTorch optimizer"
        ),

        "scheduler_state_dict": (
            "N/A - classical machine learning"
        ),

        "scaler_state_dict_mixed_precision": (
            "N/A - mixed precision is not used"
        ),

        "forward_backward_smoke_test": (
            "N/A - classical ML fit/predict "
            "smoke test was used"
        ),
    },
}


# =========================================================
# 2. Checkpoint dosyalarını atomik olarak kaydet
# =========================================================

checkpoint_names = [
    "best.ckpt",
    "last.ckpt",
    "checkpoint_quality_gate.ckpt",
]

for checkpoint_name in checkpoint_names:
    atomic_joblib_dump(
        checkpoint_state,
        DIRS["checkpoints"]
        / checkpoint_name,
        required_keys=[
            "checkpoint_schema",
            "model",
            "preprocessor",
            "threshold",
            "config",
        ],
    )


# =========================================================
# 3. best.ckpt dosyasını yeniden yükle
# =========================================================

reloaded_checkpoint = joblib.load(
    DIRS["checkpoints"] / "best.ckpt"
)


reloaded_validation_scores = (
    reloaded_checkpoint[
        "model"
    ].decision_function(
        reloaded_checkpoint[
            "preprocessor"
        ].transform(X_val)
    )
)


original_validation_scores = (
    best_model.decision_function(
        X_val_scaled
    )
)


maximum_absolute_difference = float(
    np.max(
        np.abs(
            reloaded_validation_scores
            - original_validation_scores
        )
    )
)


assert np.allclose(
    reloaded_validation_scores,
    original_validation_scores,
    rtol=1e-10,
    atol=1e-12,
), (
    "Yeniden yüklenen checkpoint aynı "
    "validation skorlarını üretmedi."
)


# =========================================================
# 4. Bağımsız model dosyasını sıfırdan yükleyip tahmin yap
# =========================================================

fresh_model_artifact = joblib.load(
    DIRS["artifacts"]
    / "svm_model.joblib"
)


probe_X = X_val[
    :min(8, len(X_val))
]


probe_scores = (
    fresh_model_artifact[
        "model"
    ].decision_function(
        fresh_model_artifact[
            "scaler"
        ].transform(probe_X)
    )
)


probe_predictions = (
    probe_scores
    >= fresh_model_artifact["threshold"]
).astype(np.int64)


assert len(probe_predictions) == len(
    probe_X
)

assert np.isfinite(
    probe_scores
).all()


# =========================================================
# 5. Fresh-load test sonucunu kaydet
# =========================================================

fresh_load_test = {
    "status": "PASS",

    "probe_count": int(
        len(probe_X)
    ),

    "predictions": (
        probe_predictions.tolist()
    ),

    "decision_scores": (
        probe_scores.tolist()
    ),

    "checkpoint_reload_max_abs_score_diff": (
        maximum_absolute_difference
    ),
}


write_json_atomic(
    fresh_load_test,
    DIRS["metrics"]
    / "fresh_load_inference_test.json"
)


# =========================================================
# 6. Genel kalite kapılarını kaydet
# =========================================================

quality_gates = {
    "schema_test": "PASS",

    "split_test": "PASS",

    "data_accounting_test": "PASS",

    "source_video_leakage_test": "PASS",

    "numerical_feature_test": "PASS",

    "classical_ml_smoke_test": "PASS",

    "train_only_scaler_test": "PASS",

    "validation_only_selection_test": "PASS",

    "pytorch_forward_backward_smoke_test": (
        "NOT_APPLICABLE_CLASSICAL_ML"
    ),

    "checkpoint_atomic_save_reload_test": (
        "PASS"
    ),

    "fresh_load_inference_test": "PASS",

    "test_set_used_for_selection": False,
}


write_json_atomic(
    quality_gates,
    DIRS["metrics"] / "quality_gates.json"
)


print(json.dumps(
    quality_gates,
    ensure_ascii=False,
    indent=2
))

print(
    "\nCheckpoint and fresh-load "
    "inference quality gates: PASS"
)

{
  "schema_test": "PASS",
  "split_test": "PASS",
  "data_accounting_test": "PASS",
  "source_video_leakage_test": "PASS",
  "numerical_feature_test": "PASS",
  "classical_ml_smoke_test": "PASS",
  "train_only_scaler_test": "PASS",
  "validation_only_selection_test": "PASS",
  "pytorch_forward_backward_smoke_test": "NOT_APPLICABLE_CLASSICAL_ML",
  "checkpoint_atomic_save_reload_test": "PASS",
  "fresh_load_inference_test": "PASS",
  "test_set_used_for_selection": false
}

Checkpoint and fresh-load inference quality gates: PASS

In [20]:
# 9) Nihai test değerlendirmesi
# Test seti model veya threshold seçiminde kullanılmaz.

# =========================================================
# 1. Örnek bazlı tahmin tablosu oluştur
# =========================================================

def build_prediction_dataframe(
    split_name,
    split_features,
    decision_scores,
    threshold
):
    true_labels = split_features["y"]

    predicted_labels = (
        decision_scores >= threshold
    ).astype(np.int64)

    return pd.DataFrame({
        "sample_id": (
            split_features["sample_id"]
        ),

        "source_video": (
            split_features["source_video"]
        ),

        "frame_index": (
            split_features["frame_index"]
        ),

        "split": split_name,

        "y_true": true_labels,

        "label": np.where(
            true_labels == 1,
            CONFIG["positive_class"],
            "real",
        ),

        "decision_score": decision_scores,

        "threshold": threshold,

        "y_pred": predicted_labels,

        "predicted_label": np.where(
            predicted_labels == 1,
            CONFIG["positive_class"],
            "real",
        ),

        "correct": (
            true_labels == predicted_labels
        ),

        "output_path": (
            split_features["output_path"]
        ),

        "run_id": RUN_ID,
    })


# =========================================================
# 2. Frame tahminlerini kaynak-video düzeyinde birleştir
# =========================================================

def aggregate_video_level(
    frame_dataframe: pd.DataFrame
):
    label_counts = (
        frame_dataframe.groupby(
            "source_video"
        )["y_true"].nunique()
    )

    assert label_counts.max() == 1, (
        "Bir kaynak videoda çelişkili "
        "gerçek sınıflar bulundu."
    )

    video_dataframe = (
        frame_dataframe.groupby(
            "source_video",
            as_index=False
        ).agg(
            y_true=("y_true", "first"),

            decision_score=(
                "decision_score",
                "mean"
            ),

            frame_count=(
                "sample_id",
                "size"
            ),
        )
    )

    video_dataframe["threshold"] = (
        selected_threshold
    )

    video_dataframe["y_pred"] = (
        video_dataframe["decision_score"]
        >= selected_threshold
    ).astype(np.int64)

    video_dataframe["label"] = np.where(
        video_dataframe["y_true"] == 1,
        CONFIG["positive_class"],
        "real",
    )

    video_dataframe["predicted_label"] = (
        np.where(
            video_dataframe["y_pred"] == 1,
            CONFIG["positive_class"],
            "real",
        )
    )

    video_dataframe["correct"] = (
        video_dataframe["y_true"]
        == video_dataframe["y_pred"]
    )

    video_dataframe["run_id"] = RUN_ID

    return video_dataframe


# =========================================================
# 3. Test özelliklerini train scaler ile dönüştür
# =========================================================

X_test_scaled = scaler.transform(
    X_test
)

assert np.isfinite(
    X_test_scaled
).all()


# =========================================================
# 4. Nihai test skorlarını üret
# =========================================================

test_scores = best_model.decision_function(
    X_test_scaled
)

assert np.isfinite(test_scores).all()


# =========================================================
# 5. Frame-level ve video-level tahminleri oluştur
# =========================================================

frame_predictions = (
    build_prediction_dataframe(
        "test",
        features["test"],
        test_scores,
        selected_threshold,
    )
)


video_predictions = (
    aggregate_video_level(
        frame_predictions
    )
)


# =========================================================
# 6. Nihai test metriklerini hesapla
# =========================================================

frame_metrics = metrics_from_scores(
    frame_predictions[
        "y_true"
    ].to_numpy(),

    frame_predictions[
        "decision_score"
    ].to_numpy(),

    selected_threshold,
)


video_metrics = metrics_from_scores(
    video_predictions[
        "y_true"
    ].to_numpy(),

    video_predictions[
        "decision_score"
    ].to_numpy(),

    selected_threshold,
)


# =========================================================
# 7. Tahmin ve metrik dosyalarını kaydet
# =========================================================

write_csv_atomic(
    frame_predictions,
    DIRS["predictions"]
    / "test_predictions_frame_level.csv"
)


write_csv_atomic(
    video_predictions,
    DIRS["predictions"]
    / "test_predictions_video_level.csv"
)


write_json_atomic(
    frame_metrics,
    DIRS["metrics"]
    / "test_metrics_frame_level.json"
)


write_json_atomic(
    video_metrics,
    DIRS["metrics"]
    / "test_metrics_video_level.json"
)


metrics_summary = pd.DataFrame([
    {
        "level": "frame",
        **frame_metrics,
    },
    {
        "level": "video",
        **video_metrics,
    },
])


write_csv_atomic(
    metrics_summary,
    DIRS["metrics"]
    / "test_metrics_summary.csv"
)


# =========================================================
# 8. Sonuçları göster
# =========================================================

print("FINAL TEST METRICS")
print(
    metrics_summary.to_string(
        index=False
    )
)

print(
    "\nFrame prediction count:",
    len(frame_predictions)
)

print(
    "Video prediction count:",
    len(video_predictions)
)

print(
    "\nFrozen test evaluation: PASS"
)

FINAL TEST METRICS
level  accuracy  precision   recall  specificity  balanced_accuracy       f1  roc_auc  average_precision  tn  fp  fn  tp
frame  0.556291   0.548673 0.794872     0.301370           0.548121 0.649215  0.58509           0.593397  44 102  32 124
video  0.612245   0.664430 0.792000     0.295775           0.543887 0.722628  0.57893           0.722733  21  50  26  99

Frame prediction count: 302
Video prediction count: 196

Frozen test evaluation: PASS

In [21]:
# 10) İngilizce ve yüksek çözünürlüklü deney grafikleri

figure_records = []


# =========================================================
# 1. Grafik kayıt ve kalite kontrol fonksiyonu
# =========================================================

def register_figure(
    figure,
    filename
):
    figure_path = (
        DIRS["figures"] / filename
    )

    width_px, height_px = save_figure(
        figure,
        figure_path
    )

    figure_records.append({
        "file": filename,
        "width_px": width_px,
        "height_px": height_px,
        "short_edge_px": min(
            width_px,
            height_px
        ),
        "quality_pass": (
            min(width_px, height_px)
            >= int(
                CONFIG[
                    "minimum_figure_short_edge_px"
                ]
            )
        ),
    })


# Ortak renkler
REAL_COLOR = "#3182CE"
FAKE_COLOR = "#DD6B20"
MODEL_COLOR = "#2F855A"
REFERENCE_COLOR = "#718096"


# =========================================================
# 2. Dataset dağılım grafiği
# =========================================================

count_dataframe = (
    eligible.groupby(
        ["split", "label"]
    )
    .size()
    .unstack(fill_value=0)
    .reindex([
        "train",
        "val",
        "test",
    ])
)


figure, axis = plt.subplots(
    figsize=(10, 6),
    dpi=int(CONFIG["figure_dpi"])
)

x_positions = np.arange(
    len(count_dataframe.index)
)

bar_width = 0.35

axis.bar(
    x_positions - bar_width / 2,
    count_dataframe.get(
        "real",
        pd.Series(
            0,
            index=count_dataframe.index
        )
    ),
    bar_width,
    label="Real",
    color=REAL_COLOR,
)

axis.bar(
    x_positions + bar_width / 2,
    count_dataframe.get(
        "fake",
        pd.Series(
            0,
            index=count_dataframe.index
        )
    ),
    bar_width,
    label="Fake",
    color=FAKE_COLOR,
)

axis.set_title(
    "Mouth ROI Dataset Distribution by Split and Class",
    fontsize=14,
    fontweight="bold",
    pad=12,
)

axis.set_xlabel(
    "Dataset Split",
    fontsize=11
)

axis.set_ylabel(
    "Number of Mouth ROI Samples",
    fontsize=11
)

axis.set_xticks(
    x_positions,
    [
        "Train",
        "Validation",
        "Test",
    ]
)

axis.legend(
    frameon=True
)

axis.grid(
    True,
    axis="y",
    alpha=0.25
)

register_figure(
    figure,
    "dataset_distribution.png"
)


# =========================================================
# 3. Validation SVM aday karşılaştırması
# =========================================================

plot_search = (
    search_dataframe.copy()
    .sort_values(
        "val_f1",
        ascending=False
    )
    .reset_index(drop=True)
)


candidate_labels = []

for row in plot_search.itertuples(
    index=False
):
    label_text = (
        f"{row.kernel} | C={row.C}"
    )

    if row.kernel == "rbf":
        label_text += (
            f" | gamma={row.gamma}"
        )

    candidate_labels.append(
        label_text
    )


figure, axis = plt.subplots(
    figsize=(12, 7),
    dpi=int(CONFIG["figure_dpi"])
)

axis.bar(
    np.arange(len(plot_search)),
    plot_search["val_f1"],
    color=MODEL_COLOR,
)

axis.set_title(
    "Validation F1 Score by SVM Candidate",
    fontsize=14,
    fontweight="bold",
    pad=12,
)

axis.set_xlabel(
    "SVM Hyperparameter Candidate",
    fontsize=11
)

axis.set_ylabel(
    "Validation F1 Score",
    fontsize=11
)

axis.set_xticks(
    np.arange(len(candidate_labels)),
    candidate_labels,
    rotation=60,
    ha="right",
)

axis.grid(
    True,
    axis="y",
    alpha=0.25
)

register_figure(
    figure,
    "svm_validation_f1_comparison.png"
)


# =========================================================
# 4. Confusion matrix fonksiyonu
# =========================================================

def create_confusion_matrix_plot(
    prediction_dataframe,
    level_name,
    filename
):
    matrix = confusion_matrix(
        prediction_dataframe["y_true"],
        prediction_dataframe["y_pred"],
        labels=[0, 1],
    )

    figure, axis = plt.subplots(
        figsize=(8, 8),
        dpi=int(CONFIG["figure_dpi"])
    )

    display = ConfusionMatrixDisplay(
        matrix,
        display_labels=[
            "Real",
            "Fake",
        ],
    )

    display.plot(
        ax=axis,
        colorbar=False,
        values_format="d",
        cmap="Blues",
    )

    axis.set_title(
        f"Test Confusion Matrix - {level_name}",
        fontsize=14,
        fontweight="bold",
        pad=12,
    )

    register_figure(
        figure,
        filename
    )


# =========================================================
# 5. ROC curve fonksiyonu
# =========================================================

def create_roc_plot(
    prediction_dataframe,
    level_name,
    filename
):
    false_positive_rate, true_positive_rate, _ = (
        roc_curve(
            prediction_dataframe["y_true"],
            prediction_dataframe[
                "decision_score"
            ],
        )
    )

    auc_value = roc_auc_score(
        prediction_dataframe["y_true"],
        prediction_dataframe[
            "decision_score"
        ],
    )

    figure, axis = plt.subplots(
        figsize=(10, 6),
        dpi=int(CONFIG["figure_dpi"])
    )

    axis.plot(
        false_positive_rate,
        true_positive_rate,
        linewidth=2,
        color=MODEL_COLOR,
        label=f"ROC AUC = {auc_value:.3f}",
    )

    axis.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        linewidth=1.5,
        color=REFERENCE_COLOR,
        label="Random Classifier",
    )

    axis.set_title(
        f"Test ROC Curve - {level_name}",
        fontsize=14,
        fontweight="bold",
        pad=12,
    )

    axis.set_xlabel(
        "False Positive Rate",
        fontsize=11
    )

    axis.set_ylabel(
        "True Positive Rate",
        fontsize=11
    )

    axis.legend(
        frameon=True,
        loc="lower right"
    )

    axis.grid(
        True,
        alpha=0.25
    )

    register_figure(
        figure,
        filename
    )


# =========================================================
# 6. Precision-recall curve fonksiyonu
# =========================================================

def create_precision_recall_plot(
    prediction_dataframe,
    level_name,
    filename
):
    precision_values, recall_values, _ = (
        precision_recall_curve(
            prediction_dataframe["y_true"],
            prediction_dataframe[
                "decision_score"
            ],
        )
    )

    average_precision = (
        average_precision_score(
            prediction_dataframe["y_true"],
            prediction_dataframe[
                "decision_score"
            ],
        )
    )

    figure, axis = plt.subplots(
        figsize=(10, 6),
        dpi=int(CONFIG["figure_dpi"])
    )

    axis.plot(
        recall_values,
        precision_values,
        linewidth=2,
        color=FAKE_COLOR,
        label=(
            "Average Precision = "
            f"{average_precision:.3f}"
        ),
    )

    axis.set_title(
        f"Test Precision-Recall Curve - {level_name}",
        fontsize=14,
        fontweight="bold",
        pad=12,
    )

    axis.set_xlabel(
        "Recall",
        fontsize=11
    )

    axis.set_ylabel(
        "Precision",
        fontsize=11
    )

    axis.legend(
        frameon=True,
        loc="lower left"
    )

    axis.grid(
        True,
        alpha=0.25
    )

    register_figure(
        figure,
        filename
    )


# =========================================================
# 7. Frame ve video confusion matrix grafikleri
# =========================================================

create_confusion_matrix_plot(
    frame_predictions,
    "Frame Level",
    "test_confusion_matrix_frame_level.png",
)

create_confusion_matrix_plot(
    video_predictions,
    "Video Level",
    "test_confusion_matrix_video_level.png",
)


# =========================================================
# 8. Frame ve video ROC grafikleri
# =========================================================

create_roc_plot(
    frame_predictions,
    "Frame Level",
    "test_roc_curve_frame_level.png",
)

create_roc_plot(
    video_predictions,
    "Video Level",
    "test_roc_curve_video_level.png",
)


# =========================================================
# 9. Frame ve video precision-recall grafikleri
# =========================================================

create_precision_recall_plot(
    frame_predictions,
    "Frame Level",
    "test_precision_recall_curve_frame_level.png",
)

create_precision_recall_plot(
    video_predictions,
    "Video Level",
    "test_precision_recall_curve_video_level.png",
)


# =========================================================
# 10. Frame-level decision score dağılımı
# =========================================================

figure, axis = plt.subplots(
    figsize=(10, 6),
    dpi=int(CONFIG["figure_dpi"])
)

real_scores = frame_predictions.loc[
    frame_predictions["y_true"] == 0,
    "decision_score",
]

fake_scores = frame_predictions.loc[
    frame_predictions["y_true"] == 1,
    "decision_score",
]

axis.hist(
    real_scores,
    bins=30,
    alpha=0.65,
    label="Real",
    color=REAL_COLOR,
)

axis.hist(
    fake_scores,
    bins=30,
    alpha=0.65,
    label="Fake",
    color=FAKE_COLOR,
)

axis.axvline(
    selected_threshold,
    linestyle="--",
    linewidth=2,
    color="#C53030",
    label=(
        f"Threshold = "
        f"{selected_threshold:.3f}"
    ),
)

axis.set_title(
    "Test Decision Score Distribution - Frame Level",
    fontsize=14,
    fontweight="bold",
    pad=12,
)

axis.set_xlabel(
    "SVM Decision Score",
    fontsize=11
)

axis.set_ylabel(
    "Number of Frames",
    fontsize=11
)

axis.legend(
    frameon=True
)

axis.grid(
    True,
    alpha=0.25
)

register_figure(
    figure,
    "test_decision_score_distribution.png"
)


# =========================================================
# 11. Grafik çözünürlük kalite kontrolü
# =========================================================

figure_audit = pd.DataFrame(
    figure_records
)

assert len(figure_audit) == 9, (
    f"Beklenen grafik sayısı 9, "
    f"oluşturulan: {len(figure_audit)}"
)

assert figure_audit[
    "quality_pass"
].all(), (
    "En az bir grafik minimum "
    "çözünürlük standardını karşılamıyor."
)


write_csv_atomic(
    figure_audit,
    DIRS["metrics"]
    / "figure_quality_audit.csv"
)


print(figure_audit.to_string(
    index=False
))

print(
    "\nHigh-resolution English figures: PASS"
)

                                       file  width_px  height_px  short_edge_px  quality_pass
                   dataset_distribution.png      1485        885            885          True
           svm_validation_f1_comparison.png      1785       1035           1035          True
      test_confusion_matrix_frame_level.png      1165       1185           1165          True
      test_confusion_matrix_video_level.png      1165       1185           1165          True
             test_roc_curve_frame_level.png      1485        885            885          True
             test_roc_curve_video_level.png      1485        885            885          True
test_precision_recall_curve_frame_level.png      1485        885            885          True
test_precision_recall_curve_video_level.png      1485        885            885          True
       test_decision_score_distribution.png      1485        885            885          True

High-resolution English figures: PASS

In [22]:
# 11) Ortam sürümleri ve deney özetini kaydet

# =========================================================
# 1. Gerçek Colab paket sürümlerini kilitle
# =========================================================

requirements_text = subprocess.check_output(
    [
        sys.executable,
        "-m",
        "pip",
        "freeze",
    ],
    text=True,
)

requirements_path = (
    RUN_DIR / "requirements_lock.txt"
)

requirements_path.write_text(
    requirements_text,
    encoding="utf-8"
)


# =========================================================
# 2. Çalışma ortamı bilgilerini kaydet
# =========================================================

environment = {
    "python": sys.version,

    "platform": platform.platform(),

    "opencv": cv2.__version__,

    "numpy": np.__version__,

    "pandas": pd.__version__,

    "scikit_learn": (
        __import__("sklearn").__version__
    ),

    "scikit_image": (
        __import__("skimage").__version__
    ),

    "run_id": RUN_ID,

    "seed": SEED,

    "region": "mouth",

    "model_name": "hog_lbp_svm",
}


write_json_atomic(
    environment,
    RUN_DIR / "environment.json"
)


# =========================================================
# 3. Deney özetini oluştur
# =========================================================

run_summary = {
    "run_id": RUN_ID,

    "status": "COMPLETED",

    "region": "mouth",

    "model": {
        "pretrained_weights": False,

        "feature_fusion": [
            "HOG",
            "LBP",
        ],

        "classifier": (
            f"{selection_summary['kernel'].upper()} SVM"
        ),

        "C": selection_summary["C"],

        "gamma": selection_summary["gamma"],

        "threshold": (
            selection_summary["threshold"]
        ),

        "positive_class": (
            CONFIG["positive_class"]
        ),
    },

    "paths": {
        "input_data": str(DATA_ROOT),

        "roi_metadata": str(
            ROI_METADATA_PATH
        ),

        "selection_metadata": str(
            SELECTION_METADATA_PATH
        ),

        "output_run": str(RUN_DIR),

        "best_checkpoint": str(
            DIRS["checkpoints"] / "best.ckpt"
        ),

        "last_checkpoint": str(
            DIRS["checkpoints"] / "last.ckpt"
        ),

        "svm_model": str(
            DIRS["artifacts"]
            / "svm_model.joblib"
        ),
    },

    "data": accounting,

    "feature_dimensions": (
        feature_dimensions
    ),

    "feature_pipeline": (
        feature_pipeline
    ),

    "selected_svm": (
        selection_summary
    ),

    "test_metrics": {
        "frame_level": frame_metrics,

        "video_level": video_metrics,
    },

    "quality_gates": quality_gates,

    "figure_count": len(
        figure_records
    ),

    "checkpoint_note": (
        "PyTorch optimizer and epoch state "
        "are not applicable to HOG, LBP and "
        "sklearn SVC. The complete SVC, "
        "train-fitted StandardScaler, "
        "validation-selected threshold, "
        "configuration and RNG states were "
        "atomically serialized and reload-tested."
    ),

    "data_leakage_note": (
        "Source-video intersections between "
        "train, validation and test were zero. "
        "StandardScaler was fitted on train only. "
        "SVM hyperparameters and threshold were "
        "selected on validation only. The frozen "
        "test set was used only for final evaluation."
    ),

    "completed_at": (
        datetime.now().isoformat()
    ),
}


write_json_atomic(
    run_summary,
    RUN_DIR / "run_summary.json"
)


# =========================================================
# 4. Kaydedilen özeti yeniden açıp doğrula
# =========================================================

with (
    RUN_DIR / "run_summary.json"
).open(
    "r",
    encoding="utf-8"
) as file:
    reloaded_run_summary = json.load(file)


assert (
    reloaded_run_summary["status"]
    == "COMPLETED"
)

assert (
    reloaded_run_summary["region"]
    == "mouth"
)

assert (
    reloaded_run_summary[
        "figure_count"
    ] == 9
)

assert (
    reloaded_run_summary[
        "selected_svm"
    ][
        "test_set_used_for_selection"
    ] is False
)


print("Environment lock: PASS")
print("Run summary: PASS")
print("Run ID:", RUN_ID)
print("Run directory:", RUN_DIR)
print("Figure count:", len(figure_records))

Environment lock: PASS
Run summary: PASS
Run ID: 20260807_2034_mouth_hog_lbp_svm_seed42
Run directory: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar/20260807_2034_mouth_hog_lbp_svm_seed42
Figure count: 9

In [23]:
# 12) Nihai çıktı manifesti ve deney tamamlama kontrolü

# =========================================================
# 1. Zorunlu çıktı dosyalarını doğrula
# =========================================================

required_output_files = [
    RUN_DIR / "config_resolved.yaml",
    RUN_DIR / "requirements_lock.txt",
    RUN_DIR / "environment.json",
    RUN_DIR / "run_summary.json",

    DIRS["checkpoints"] / "best.ckpt",
    DIRS["checkpoints"] / "last.ckpt",

    DIRS["artifacts"] / "svm_model.joblib",
    DIRS["artifacts"] / "metadata_used.csv",
    DIRS["artifacts"] / "features_train.npz",
    DIRS["artifacts"] / "features_val.npz",
    DIRS["artifacts"] / "features_test.npz",

    DIRS["metrics"] / "data_accounting.json",
    DIRS["metrics"] / "svm_validation_search.csv",
    DIRS["metrics"] / "svm_selection.json",
    DIRS["metrics"] / "quality_gates.json",
    DIRS["metrics"] / "test_metrics_summary.csv",
    DIRS["metrics"] / "figure_quality_audit.csv",

    DIRS["predictions"]
    / "test_predictions_frame_level.csv",

    DIRS["predictions"]
    / "test_predictions_video_level.csv",
]


missing_outputs = [
    str(path)
    for path in required_output_files
    if not path.exists()
]


assert not missing_outputs, (
    "Eksik zorunlu deney çıktıları var:\n"
    + "\n".join(missing_outputs)
)


empty_outputs = [
    str(path)
    for path in required_output_files
    if path.stat().st_size == 0
]


assert not empty_outputs, (
    "Boş çıktı dosyaları var:\n"
    + "\n".join(empty_outputs)
)


# =========================================================
# 2. Dokuz grafik dosyasını doğrula
# =========================================================

figure_files = sorted(
    DIRS["figures"].glob("*.png")
)


assert len(figure_files) == 9, (
    f"Beklenen grafik sayısı 9, "
    f"bulunan: {len(figure_files)}"
)


for figure_path in figure_files:
    with Image.open(figure_path) as image:
        width_px, height_px = image.size

    assert min(
        width_px,
        height_px
    ) >= int(
        CONFIG[
            "minimum_figure_short_edge_px"
        ]
    ), (
        "Grafik çözünürlüğü yetersiz: "
        f"{figure_path.name}"
    )


# =========================================================
# 3. Deney tamamlama işaretini oluştur
# =========================================================

completion_marker = {
    "run_id": RUN_ID,

    "status": "COMPLETED",

    "region": "mouth",

    "model": "HOG + LBP + SVM",

    "selected_kernel": (
        selection_summary["kernel"]
    ),

    "selected_C": (
        selection_summary["C"]
    ),

    "selected_gamma": (
        selection_summary["gamma"]
    ),

    "selected_threshold": (
        selection_summary["threshold"]
    ),

    "frame_test_metrics": frame_metrics,

    "video_test_metrics": video_metrics,

    "quality_gates_passed": True,

    "figure_count": len(
        figure_files
    ),

    "completed_at": (
        datetime.now().isoformat()
    ),
}


write_json_atomic(
    completion_marker,
    RUN_DIR / "experiment_completed.json"
)


# =========================================================
# 4. Bütün çıktı dosyalarının manifestini oluştur
# =========================================================
#
# Manifest kendi hash değerini içeremez.
# Bu nedenle output_manifest.csv bilinçli olarak dışlanır.

manifest_rows = []


for file_path in sorted(
    RUN_DIR.rglob("*")
):
    if not file_path.is_file():
        continue

    if file_path.name == "output_manifest.csv":
        continue

    if file_path.name.endswith(".tmp"):
        continue

    manifest_rows.append({
        "relative_path": str(
            file_path.relative_to(
                RUN_DIR
            )
        ),

        "size_bytes": int(
            file_path.stat().st_size
        ),

        "sha256": sha256_file(
            file_path
        ),
    })


manifest_dataframe = pd.DataFrame(
    manifest_rows
)


assert len(manifest_dataframe) > 0, (
    "Çıktı manifesti boş oluşturuldu."
)


assert (
    manifest_dataframe["size_bytes"] > 0
).all(), (
    "Manifest içinde boş dosya bulundu."
)


write_csv_atomic(
    manifest_dataframe,
    RUN_DIR / "output_manifest.csv"
)


# =========================================================
# 5. Geçici dosya kalmadığını doğrula
# =========================================================

temporary_files = [
    str(path)
    for path in RUN_DIR.rglob("*.tmp")
]


assert not temporary_files, (
    "Run klasöründe geçici dosyalar kaldı:\n"
    + "\n".join(temporary_files)
)


# =========================================================
# 6. Manifesti yeniden açıp doğrula
# =========================================================

reloaded_manifest = pd.read_csv(
    RUN_DIR / "output_manifest.csv"
)


assert len(reloaded_manifest) == len(
    manifest_dataframe
)


assert reloaded_manifest[
    "relative_path"
].is_unique


# =========================================================
# 7. Nihai deney özetini göster
# =========================================================

print("=" * 80)
print("EXPERIMENT COMPLETED")
print("=" * 80)

print("Run ID:", RUN_ID)
print("Region: Mouth")
print("Model: HOG + LBP + SVM")

print(
    "Selected SVM:",
    selection_summary["kernel"],
    "| C =",
    selection_summary["C"],
    "| gamma =",
    selection_summary["gamma"],
)

print("\nFrame-level final test metrics:")
print(json.dumps(
    json_safe(frame_metrics),
    ensure_ascii=False,
    indent=2
))

print("\nVideo-level final test metrics:")
print(json.dumps(
    json_safe(video_metrics),
    ensure_ascii=False,
    indent=2
))

print(
    "\nGenerated output files:",
    len(manifest_dataframe)
)

print(
    "Generated figures:",
    len(figure_files)
)

print(
    "Output directory:",
    RUN_DIR
)

print("=" * 80)
print("ALL FINAL QUALITY GATES: PASS")
print("=" * 80)

================================================================================
EXPERIMENT COMPLETED
================================================================================
Run ID: 20260807_2034_mouth_hog_lbp_svm_seed42
Region: Mouth
Model: HOG + LBP + SVM
Selected SVM: rbf | C = 1.0 | gamma = 0.001

Frame-level final test metrics:
{
  "accuracy": 0.5562913907284768,
  "precision": 0.5486725663716814,
  "recall": 0.7948717948717948,
  "specificity": 0.3013698630136986,
  "balanced_accuracy": 0.5481208289427467,
  "f1": 0.6492146596858639,
  "roc_auc": 0.5850895679662804,
  "average_precision": 0.5933972300707224,
  "tn": 44,
  "fp": 102,
  "fn": 32,
  "tp": 124
}

Video-level final test metrics:
{
  "accuracy": 0.6122448979591837,
  "precision": 0.6644295302013423,
  "recall": 0.792,
  "specificity": 0.29577464788732394,
  "balanced_accuracy": 0.543887323943662,
  "f1": 0.7226277372262774,
  "roc_auc": 0.5789295774647887,
  "average_precision": 0.7227328268884463,
  "tn": 21,
  "fp": 50,
  "fn": 26,
  "tp": 99
}

Generated output files: 34
Generated figures: 9
Output directory: /content/drive/MyDrive/AISC DeepFake Çalışmaları/Deneyler/Dilara/Deney 1/Sonuçlar/20260807_2034_mouth_hog_lbp_svm_seed42
================================================================================
ALL FINAL QUALITY GATES: PASS
================================================================================